<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <eSubpackages name="com.IDG.utils">
    <eClassifiers xsi:type="ecore:EClass" name="MapValidityHelper"/>
  </eSubpackages>
  <eSubpackages name="com.IDG.controller">
    <eClassifiers xsi:type="ecore:EClass" name="Colosseum"/>
    <eClassifiers xsi:type="ecore:EClass" name="Game"/>
    <eClassifiers xsi:type="ecore:EClass" name="GameController"/>
    <eClassifiers xsi:type="ecore:EClass" name="GameFileManager"/>
    <eClassifiers xsi:type="ecore:EClass" name="LayoutManager"/>
  </eSubpackages>
  <eSubpackages name="com.IDG.mapBuilder">
    <eClassifiers xsi:type="ecore:EClass" name="ListenToLoad"/>
    <eClassifiers xsi:type="ecore:EClass" name="ListenToSave"/>
    <eClassifiers xsi:type="ecore:EClass" name="Laod"/>
    <eClassifiers xsi:type="ecore:EClass" name="mapbuilder"/>
    <eClassifiers xsi:type="ecore:EClass" name="MapButton"/>
    <eClassifiers xsi:type="ecore:EClass" name="MapEditorView"/>
    <eClassifiers xsi:type="ecore:EClass" name="PopClickListener"/>
    <eClassifiers xsi:type="ecore:EClass" name="PopUpDemo"/>
    <eClassifiers xsi:type="ecore:EClass" name="Wall"/>
  </eSubpackages>
  <eSubpackages name="com.MapSimulator">
    <eClassifiers xsi:type="ecore:EClass" name="Arsenal"/>
    <eClassifiers xsi:type="ecore:EClass" name="Block"/>
    <eClassifiers xsi:type="ecore:EClass" name="KeyHandel"/>
    <eClassifiers xsi:type="ecore:EClass" name="MapSimulatorView"/>
    <eClassifiers xsi:type="ecore:EClass" name="Room"/>
    <eClassifiers xsi:type="ecore:EClass" name="Tower"/>
  </eSubpackages>
</ecore:EPackage>
